import {
  useAuth0,
  useBattleDotNet,
  useCognito,
  useDiscord,
  useGithub,
  useGoogle,
  useKeyclock,
  useLinkedIn,
  useMicrosoft,
  usePaypal,
  useSpotify,
  useSteam,
  useTwitch,
  useX,
  useXsuaa,
  useYandex,
} from "../providers";

export const providerFunction = {
  Auth0: useAuth0,
  BattleDotNet: useBattleDotNet,
  Cognito: useCognito,
  Discord: useDiscord,
  Github: useGithub,
  Google: useGoogle,
  Keycloak: useKeyclock,
  LinkedIn: useLinkedIn,
  Microsoft: useMicrosoft,
  Paypal: usePaypal,
  Spotify: useSpotify,
  Steam: useSteam,
  Twitch: useTwitch,
  X: useX,
  Xsuaa: useXsuaa,
  Yandex: useYandex,
};
