import {
  useAuth0,
  useBattleDotNet,
  useCognito,
  useDiscord,
  useGithub,
  useGoogle,
  useKeyclock,
  useLinkedIn,
  useMicrosoft,
  usePaypal,
  useSpotify,
  useSteam,
  useTwitch,
  useX,
  useXsuaa,
  useYandex,
} from "../providers";

export const providerFunction = {
  auth0: useAuth0,
  battleDotNet: useBattleDotNet,
  cognito: useCognito,
  discord: useDiscord,
  github: useGithub,
  google: useGoogle,
  keycloak: useKeyclock,
  linkedIn: useLinkedIn,
  microsoft: useMicrosoft,
  paypal: usePaypal,
  spotify: useSpotify,
  steam: useSteam,
  twitch: useTwitch,
  x: useX,
  xsuaa: useXsuaa,
  yandex: useYandex,
};
